schema: "2"
name: ethr
slug: ethr
owner: acl-dev-team-data-infrastructure@getweave.com
slack: "#squad-data-infra-alerts"
namespace: data-infra
deploy:
  wsf-prod-1-gke1-west3:
    service:
    - name: ethr
      ports:
      - name: tcp
        number: 9999
      - name: udp
        number: 9999
        protocol: UDP
    resources:
      scaling:
        replicas: 1
    livenessProbe: {}
    readinessProbe: {}
    ingress:
    - host: ethr.weavelab.ninja
      public: true
      paths:
      - path: /
        serviceName: ethr
        servicePort: 9999
    #featureFlags:
    #  auto-deploy: true
